package proyecto;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author isaac
 */
public class Equipo extends javax.swing.JFrame {

    String mouse="",teclado="", monitor="", CodigoCPU="";
    public Equipo() {
        initComponents();
        this.txtcodigo.setEnabled(false);
        this.setLocationRelativeTo(null);
        this.Labtxt.setEnabled(false);
        this.txtMonitor.setEnabled(false);
        this.jPanel6.setVisible(false);
        this.jPanel1.setVisible(false);
        this.jPanel3.setVisible(false);
        this.jPanel4.setVisible(false);
        this.jPanel5.setVisible(false);
        this.jPanel7.setVisible(false);
        this.btnActualizar.setEnabled(false);
        mostrarDatos("");
        
    }
    void mostrarDatos( String valor){
        DefaultTableModel modelo  = new DefaultTableModel(); 
        
        modelo.addColumn("Codigo");
        modelo.addColumn("Laboratorio");
        modelo.addColumn("No.Asignado");
        modelo.addColumn("IP");
        modelo.addColumn("CPU");
        modelo.addColumn("Capacidad");
        
        tbLaboratorio.setModel(modelo);
        String sql = "";
        if(valor.equals(""))
        {
        sql = "Select a.codigoEquipo, c.nombreLaboratorio, a.numeroAsignado, a.ipEquipo, b.codigoCpu, b.capacidadRamEquipo from equipo a inner join cpu b on a.codigoEquipo=b.codigoEquipo inner join laboratorio c on a.codigoLaboratorio=c.codigoLaboratorio";
        }
        else{
        sql = "Select * from equipo where numeroAsignado like  '"+valor+"%' ";
        }
        String []datos = new String[6];
        
        Conectar con=new Conectar();
        Connection reg=con.getConnection();
        
        try {
            Statement st = reg.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
            datos[0] = rs.getString(1);
            datos[1] = rs.getString(2);
            datos[2] = rs.getString(3);
            datos[3] = rs.getString(4);
            datos[4] = rs.getString(5);
            datos[5] = rs.getString(6);
            modelo.addRow(datos);
            
            }
            tbLaboratorio.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(RegistroLaboratorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        NumeroAsignadotxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dbMonitor = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        iptxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        codigobtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        RegresarBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Labtxt = new javax.swing.JTextField();
        txtMonitor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        perifericobtn = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLaboratorio = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dbTeclado = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        txtTeclado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMouse = new javax.swing.JTextField();
        perifericobtn1 = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dbMouse = new javax.swing.JTable();
        GuardarBtnEquipo = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        codigobtn1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        dbLab = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        dbperifericos = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtCPU = new javax.swing.JTextField();
        perifericobtn2 = new javax.swing.JToggleButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        dbCPU = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem3.setText("Ingresar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem3);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NumeroAsignadotxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Numero de equipo:");

        dbMonitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dbMonitor.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dbMonitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbMonitorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(dbMonitor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        iptxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("IP Equipo:");

        codigobtn.setText("...");
        codigobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigobtnActionPerformed(evt);
            }
        });

        RegresarBtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        RegresarBtn.setText("Regresar");
        RegresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarBtnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Laboratorio:");

        Labtxt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Labtxt.setEnabled(false);

        txtMonitor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMonitor.setEnabled(false);
        txtMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonitorActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Monitor: ");

        perifericobtn.setText("...");
        perifericobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perifericobtnActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 160, 30));

        lblNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblNombre.setText("Nombre: ");
        jPanel2.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        tbLaboratorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbLaboratorio.setComponentPopupMenu(jPopupMenu1);
        tbLaboratorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLaboratorioMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbLaboratorio);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 500, 200));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Codigo equipo:");

        txtcodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dbTeclado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dbTeclado.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dbTeclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbTecladoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dbTeclado);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel8.setText("Teclado:");

        txtTeclado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTeclado.setEnabled(false);
        txtTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTecladoActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel9.setText("Mouse: ");

        txtMouse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMouse.setEnabled(false);
        txtMouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMouseActionPerformed(evt);
            }
        });

        perifericobtn1.setText("...");
        perifericobtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perifericobtn1ActionPerformed(evt);
            }
        });

        dbMouse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dbMouse.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dbMouse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbMouseMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(dbMouse);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        GuardarBtnEquipo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        GuardarBtnEquipo.setText("Guardar");
        GuardarBtnEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBtnEquipoActionPerformed(evt);
            }
        });

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        codigobtn1.setText("...");
        codigobtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigobtn1ActionPerformed(evt);
            }
        });

        dbLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dbLab.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dbLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbLabMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(dbLab);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Perifericos"));

        dbperifericos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dbperifericos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dbperifericos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbperifericosMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(dbperifericos);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("CPU:");

        txtCPU.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCPU.setEnabled(false);
        txtCPU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPUActionPerformed(evt);
            }
        });

        perifericobtn2.setText("...");
        perifericobtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perifericobtn2ActionPerformed(evt);
            }
        });

        dbCPU.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dbCPU.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        dbCPU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dbCPUMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(dbCPU);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel12.setText("Mantenimiento Equipo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(codigobtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(5, 5, 5)
                                        .addComponent(txtMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(perifericobtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(perifericobtn1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel11)
                                        .addGap(39, 39, 39)
                                        .addComponent(txtCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(perifericobtn2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GuardarBtnEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RegresarBtn))
                        .addContainerGap(124, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel7))
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel4)))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NumeroAsignadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(iptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Labtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(codigobtn1)))
                                .addGap(10, 10, 10)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(jLabel7)
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(NumeroAsignadotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(iptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Labtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codigobtn1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigobtn))
                        .addGap(11, 11, 11)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perifericobtn))
                        .addGap(22, 22, 22)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perifericobtn1))
                        .addGap(22, 22, 22)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(perifericobtn2))
                        .addGap(12, 12, 12)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(GuardarBtnEquipo)
                        .addGap(23, 23, 23)
                        .addComponent(btnActualizar))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(RegresarBtn))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarBtnEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBtnEquipoActionPerformed
        // TODO add your handling code here:
        Conectar con=new Conectar();
        Connection reg=con.getConnection();
        String numeroAsignado = this.NumeroAsignadotxt.getText();
        String codigo_equ="";
         try{
             
             String numeroAsignado1 = "";
            String sql = "select * FROM equipo where numeroAsignado ='" +numeroAsignado+"' AND codigoEquipo !='" +this.txtcodigo.getText()+"' AND codigoLaboratorio='" +this.Labtxt.getText()+"'";
            Statement st = reg.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while(rs.next())
            {
                numeroAsignado1 = rs.getString("numeroAsignado");
            }

            if(numeroAsignado.equals(numeroAsignado1))
            {
                JOptionPane.showMessageDialog(null, "Numero ya asignado");
            }
            else{
            PreparedStatement obj = reg.prepareStatement("INSERT INTO equipo (numeroAsignado,ipEquipo,codigoLaboratorio) values(?,?,?)");
                
            obj.setString(1,this.NumeroAsignadotxt.getText());
            obj.setString(2,this.iptxt.getText());
            obj.setString(3,this.Labtxt.getText());
            obj.executeUpdate();
            
            ResultSet rx = Conectar.getTabla("select * from equipo where numeroAsignado='"+this.NumeroAsignadotxt.getText()+"'");
            while(rx.next()){
                codigo_equ=rx.getString("codigoEquipo");
            }
            
            obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo='"+codigo_equ+"', estadoPeriferico='OCUPADO' where codigoPeriferico='"+this.txtMonitor.getText()+"'");
            obj.executeUpdate();
            obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo='"+codigo_equ+"', estadoPeriferico='OCUPADO' where codigoPeriferico='"+this.txtTeclado.getText()+"'");
            obj.executeUpdate();
            obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo='"+codigo_equ+"', estadoPeriferico='OCUPADO' where codigoPeriferico='"+this.txtMouse.getText()+"'");
            obj.executeUpdate();
            obj=reg.prepareStatement("UPDATE cpu SET codigoEquipo='"+codigo_equ+"', estadoCpu='OCUPADO' where codigoCpu='"+this.txtCPU.getText()+"'");
            obj.executeUpdate();
            JOptionPane.showMessageDialog(null, "Guardado con exito");
            }
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Equipo.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_GuardarBtnEquipoActionPerformed

    private void dbMonitorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbMonitorMouseClicked
        int fila=this.dbMonitor.getSelectedRow();
        if(fila>=0)
        {
            this.txtMonitor.setText(this.dbMonitor.getValueAt(fila, 0).toString());
        
        }
        
        this.jPanel1.setVisible(false);
    }//GEN-LAST:event_dbMonitorMouseClicked

    private void RegresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarBtnActionPerformed
        // TODO add your handling code here:
        Inventario men = new Inventario();

        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegresarBtnActionPerformed

    private void perifericobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perifericobtnActionPerformed
        this.jPanel4.setVisible(true);
        DefaultTableModel modelo2 = new DefaultTableModel();
        ResultSet rx = Conectar.getTabla("SELECT a.codigoPeriferico,b.nombrePeriferico, c.nombreMarca, a.seriePeriferico FROM perifericos a INNER JOIN tipoperiferico b on a.codigoTipoPeriferico=b.codigoTipoPeriferico INNER JOIN marca c on a.codigoMarca=c.codigoMarca where b.nombrePeriferico='mouse' and a.estadoPeriferico='disponible'");
        modelo2.setColumnIdentifiers(new Object[]{"Codigo","Periferico","Marca","Serie"});
        try
        {
            while(rx.next()){
                modelo2.addRow(new Object[]{rx.getString("codigoPeriferico"),rx.getString("nombrePeriferico"), rx.getString("nombreMarca"), rx.getString("seriePeriferico")});
            }
            this.dbMouse.setModel(modelo2);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_perifericobtnActionPerformed

    private void txtMonitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonitorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonitorActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        mostrarDatos(txtBuscar.getText());
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        
        String numeroAsignado = this.NumeroAsignadotxt.getText();
        String ip = this.iptxt.getText().toUpperCase();
        
        String equipo = null;
        
        Conectar con=new Conectar();
        Connection reg=con.getConnection();
        try
        {
            String numeroAsignado1 = "";
            String sql = "select * FROM equipo where numeroAsignado ='" +numeroAsignado+"' AND codigoEquipo !='" +this.txtcodigo.getText()+"' AND codigoLaboratorio='" +this.Labtxt.getText()+"'";
            Statement st = reg.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while(rs.next())
            {
                numeroAsignado1 = rs.getString("numeroAsignado");
            }

            if(numeroAsignado.equals(numeroAsignado1))
            {
                JOptionPane.showMessageDialog(null, "Numero ya asignado");
            }
            else
            {
                PreparedStatement obj=reg.prepareStatement("UPDATE equipo SET numeroAsignado='"+this.NumeroAsignadotxt.getText()+"',ipEquipo='"+this.iptxt.getText()+"'WHERE codigoEquipo='"+this.txtcodigo.getText()+"'");
                obj.executeUpdate();
                
                
                obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo="+equipo+", estadoPeriferico='DISPONIBLE' where codigoEquipo='"+monitor+"'");
                obj.executeUpdate();
                obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo="+equipo+", estadoPeriferico='DISPONIBLE' where codigoEquipo='"+teclado+"'");
                obj.executeUpdate();
                obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo="+equipo+", estadoPeriferico='DISPONIBLE' where codigoEquipo='"+mouse+"'");
                obj.executeUpdate();    
                obj=reg.prepareStatement("UPDATE cpu SET codigoEquipo="+equipo+", estadoCpu='DISPONIBLE' where codigoCpu='"+CodigoCPU+"'");
                obj.executeUpdate();
    
                obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo='"+this.txtcodigo.getText()+"', estadoPeriferico='OCUPADO' where codigoPeriferico='"+this.txtMonitor.getText()+"'");
                obj.executeUpdate();
                obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo='"+this.txtcodigo.getText()+"', estadoPeriferico='OCUPADO' where codigoPeriferico='"+this.txtTeclado.getText()+"'");
                obj.executeUpdate();
                obj=reg.prepareStatement("UPDATE perifericos SET codigoEquipo='"+this.txtcodigo.getText()+"', estadoPeriferico='OCUPADO' where codigoPeriferico='"+this.txtMouse.getText()+"'");
                obj.executeUpdate();
                obj=reg.prepareStatement("UPDATE cpu SET codigoEquipo='"+this.txtcodigo.getText()+"', estadoCpu='OCUPADO' where codigoCpu='"+this.txtCPU.getText()+"'");
                obj.executeUpdate();
                

                JOptionPane.showMessageDialog(null, "Guardado con exito");
                mostrarDatos("");

                this.txtcodigo.setText("");
                this.NumeroAsignadotxt.setText("");
                this.iptxt.setText("");
                this.txtBuscar.setText("");
               // this.btnIngresar.setEnabled(true);
                this.btnActualizar.setEnabled(false);
                this.GuardarBtnEquipo.setEnabled(true);
            }

        }
        catch(SQLException ex)
        {
            Logger.getLogger(RegistroLaboratorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void dbTecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbTecladoMouseClicked
        // TODO add your handling code here:
         int fila=this.dbTeclado.getSelectedRow();
        if(fila>=0)
        {
            this.txtTeclado.setText(this.dbTeclado.getValueAt(fila, 0).toString());
        
        }
        this.jPanel3.setVisible(false);
    }//GEN-LAST:event_dbTecladoMouseClicked

    private void txtTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTecladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTecladoActionPerformed

    private void txtMouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMouseActionPerformed

    private void perifericobtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perifericobtn1ActionPerformed
        this.jPanel3.setVisible(true);
        DefaultTableModel modelo2 = new DefaultTableModel();
        ResultSet rx = Conectar.getTabla("SELECT a.codigoPeriferico,b.nombrePeriferico, c.nombreMarca, a.seriePeriferico FROM perifericos a INNER JOIN tipoperiferico b on a.codigoTipoPeriferico=b.codigoTipoPeriferico INNER JOIN marca c on a.codigoMarca=c.codigoMarca where b.nombrePeriferico='teclado' and a.estadoPeriferico='disponible'");
        modelo2.setColumnIdentifiers(new Object[]{"Codigo","Periferico","Marca","Serie"});
        try
        {
            while(rx.next()){
                modelo2.addRow(new Object[]{rx.getString("codigoPeriferico"),rx.getString("nombrePeriferico"), rx.getString("nombreMarca"), rx.getString("seriePeriferico")});
            }
            this.dbTeclado.setModel(modelo2);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_perifericobtn1ActionPerformed

    private void dbMouseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbMouseMouseClicked
         int fila=this.dbMouse.getSelectedRow();
        if(fila>=0)
        {
            this.txtMouse.setText(this.dbMouse.getValueAt(fila, 0).toString());
        
        }
        this.jPanel4.setVisible(false);
    }//GEN-LAST:event_dbMouseMouseClicked

    private void codigobtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigobtn1ActionPerformed
        this.jPanel5.setVisible(true);
        DefaultTableModel modelo2 = new DefaultTableModel();
        ResultSet rx = Conectar.getTabla("select * from laboratorio");
        modelo2.setColumnIdentifiers(new Object[]{"Codigo","Nombre"});
        try
        {
            while(rx.next()){
                modelo2.addRow(new Object[]{rx.getString("codigoLaboratorio"),rx.getString("nombreLaboratorio")});
            }
            this.dbLab.setModel(modelo2);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_codigobtn1ActionPerformed

    private void dbLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbLabMouseClicked
        int fila=this.dbLab.getSelectedRow();
        if(fila>=0)
        {
            this.Labtxt.setText(this.dbLab.getValueAt(fila, 0).toString());
        
        }
        this.jPanel5.setVisible(false);
    }//GEN-LAST:event_dbLabMouseClicked

    private void codigobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigobtnActionPerformed
        // TODO add your handling code here:
        this.jPanel1.setVisible(true);
        DefaultTableModel modelo2 = new DefaultTableModel();
        ResultSet rx = Conectar.getTabla("SELECT a.codigoPeriferico,b.nombrePeriferico, c.nombreMarca, a.seriePeriferico FROM perifericos a INNER JOIN tipoperiferico b on a.codigoTipoPeriferico=b.codigoTipoPeriferico INNER JOIN marca c on a.codigoMarca=c.codigoMarca where b.nombrePeriferico='monitor' and a.estadoPeriferico='disponible'");
        modelo2.setColumnIdentifiers(new Object[]{"Codigo","Periferico","Marca","Serie"});
        try
        {
            while(rx.next()){
                modelo2.addRow(new Object[]{rx.getString("codigoPeriferico"),rx.getString("nombrePeriferico"), rx.getString("nombreMarca"), rx.getString("seriePeriferico")});
            }
            this.dbMonitor.setModel(modelo2);
        }
        catch(Exception e){
            System.out.println(e);
        }

    }//GEN-LAST:event_codigobtnActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
        this.btnActualizar.setEnabled(false);
        int fila = this.tbLaboratorio.getSelectedRow();
        if(fila >=0)
        {
            this.btnActualizar.setEnabled(true);
            this.txtcodigo.setText(tbLaboratorio.getValueAt(fila,0).toString());
            this.Labtxt.setText(tbLaboratorio.getValueAt(fila,1).toString());
            this.NumeroAsignadotxt.setText(tbLaboratorio.getValueAt(fila,2).toString());
            this.iptxt.setText(tbLaboratorio.getValueAt(fila,3).toString());
            this.txtCPU.setText(tbLaboratorio.getValueAt(fila,4).toString());
            this.GuardarBtnEquipo.setEnabled(false);
            
            this.txtMouse.setText(dbperifericos.getValueAt(0,0).toString());
            this.txtMonitor.setText(dbperifericos.getValueAt(1,0).toString());
            this.txtTeclado.setText(dbperifericos.getValueAt(2,0).toString());
            
            mouse = this.txtMouse.getText();
            teclado=this.txtTeclado.getText();
            monitor=this.txtMonitor.getText();
            CodigoCPU=this.txtCPU.getText();
        }
        else{
        JOptionPane.showMessageDialog(null,"no selecciono fila");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

        Conectar con=new Conectar();
        Connection reg=con.getConnection();
        try
        {
            int fila = tbLaboratorio.getSelectedRow();
            String codigo ="";
            codigo = tbLaboratorio.getValueAt(fila,0).toString();
            PreparedStatement obj=reg.prepareStatement("Delete from cliente Where codigoIdCliente='"+codigo+"'");
            obj.executeUpdate();
            mostrarDatos("");
            this.tbLaboratorio.setEnabled(true);
            this.btnActualizar.setEnabled(false);
        }
        catch(SQLException ex)
        {
            Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void dbperifericosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbperifericosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dbperifericosMouseClicked

    private void tbLaboratorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLaboratorioMouseClicked
        String codigo_e="";
        this.jPanel6.setVisible(true);
        int fila=this.tbLaboratorio.getSelectedRow();
        if(fila>=0)
        {
            codigo_e=(this.tbLaboratorio.getValueAt(fila, 0).toString());
        
        }
        DefaultTableModel modelo2 = new DefaultTableModel();
        ResultSet rx = Conectar.getTabla("SELECT a.codigoPeriferico,b.nombrePeriferico, c.nombreMarca, a.seriePeriferico FROM perifericos a INNER JOIN tipoperiferico b on a.codigoTipoPeriferico=b.codigoTipoPeriferico INNER JOIN marca c on a.codigoMarca=c.codigoMarca where a.codigoEquipo='"+codigo_e+"'");
        modelo2.setColumnIdentifiers(new Object[]{"Codigo","Periferico","Marca","Serie"});
        try
        {
            while(rx.next()){
                modelo2.addRow(new Object[]{rx.getString("codigoPeriferico"),rx.getString("nombrePeriferico"), rx.getString("nombreMarca"), rx.getString("seriePeriferico")});
            }
            this.dbperifericos.setModel(modelo2);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_tbLaboratorioMouseClicked

    private void txtCPUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPUActionPerformed

    private void perifericobtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perifericobtn2ActionPerformed
        this.jPanel7.setVisible(true);
        DefaultTableModel modelo2 = new DefaultTableModel();
        ResultSet rx = Conectar.getTabla("SELECT a.codigoCpu, b.nombreMarca, a.serieCpu, a.cantidadRamEquipo, a.capacidadRamEquipo FROM cpu a INNER JOIN marca b on a.codigoMarca=b.codigoMarca where estadoCpu='disponible'");
        modelo2.setColumnIdentifiers(new Object[]{"Codigo","Marca","Serie", "Cantidad Ram", "Capacidad Ram"});
        try
        {
            while(rx.next()){
                modelo2.addRow(new Object[]{rx.getString("codigoCpu"),rx.getString("nombreMarca"), rx.getString("serieCpu"), rx.getString("cantidadRamEquipo"),rx.getString("capacidadRamEquipo")});
            }
            this.dbCPU.setModel(modelo2);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_perifericobtn2ActionPerformed

    private void dbCPUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dbCPUMouseClicked
        int fila=this.dbCPU.getSelectedRow();
        if(fila>=0)
        {
            this.txtCPU.setText(this.dbCPU.getValueAt(fila, 0).toString());
        
        }
        this.jPanel7.setVisible(false);
    }//GEN-LAST:event_dbCPUMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Equipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Equipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GuardarBtnEquipo;
    private javax.swing.JTextField Labtxt;
    private javax.swing.JTextField NumeroAsignadotxt;
    private javax.swing.JButton RegresarBtn;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton codigobtn;
    private javax.swing.JButton codigobtn1;
    private javax.swing.JTable dbCPU;
    private javax.swing.JTable dbLab;
    private javax.swing.JTable dbMonitor;
    private javax.swing.JTable dbMouse;
    private javax.swing.JTable dbTeclado;
    private javax.swing.JTable dbperifericos;
    private javax.swing.JTextField iptxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JToggleButton perifericobtn;
    private javax.swing.JToggleButton perifericobtn1;
    private javax.swing.JToggleButton perifericobtn2;
    private javax.swing.JTable tbLaboratorio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCPU;
    private javax.swing.JTextField txtMonitor;
    private javax.swing.JTextField txtMouse;
    private javax.swing.JTextField txtTeclado;
    private javax.swing.JTextField txtcodigo;
    // End of variables declaration//GEN-END:variables
}
