/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class memoriaRam extends javax.swing.JFrame {

    /**
     * Creates new form memoriaRam
     */
    public memoriaRam() {
        initComponents();
        
         this.lblIngresar.setVisible(false);
        this.lblModificar.setVisible(false);
        this.lblCodigo.setVisible(false);
        this.lblCapacidad.setVisible(false);
        this.lblCodigoMarca.setVisible(false);
        this.lblCodigoCpu.setVisible(false);
        this.btnActualizar.setVisible(false);
        this.btnIngresar.setVisible(false);
        this.txtCapacidad.setVisible(false);
         this.txtCodigoM.setVisible(false);
        this.txtCodigoCPU.setVisible(false);
        this.btnBuscar.setVisible(false);
        this.txtCodigo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresar = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        btnIngresar11 = new javax.swing.JButton();
        btnActualizar11 = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblCodigoMarca = new javax.swing.JLabel();
        txtCodigoM = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        txtCapacidad = new javax.swing.JTextField();
        lblCodigoCpu = new javax.swing.JLabel();
        txtCodigoCPU = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngresar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblIngresar.setText("Registrar Memoria");
        getContentPane().add(lblIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        lblModificar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblModificar.setText("Modificar Memoria");
        getContentPane().add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        btnIngresar11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIngresar11.setText("Modificar");
        btnIngresar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        btnActualizar11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnActualizar11.setText("Registrar");
        btnActualizar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCodigo.setText("Codigo Memoria:");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, -1));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 110, -1));

        lblCodigoMarca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCodigoMarca.setText("Codigo Marca:");
        getContentPane().add(lblCodigoMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 160, -1));

        txtCodigoM.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCodigoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoMKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 80, -1));

        lblCapacidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCapacidad.setText("Capacidad:");
        getContentPane().add(lblCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 140, -1));

        txtCapacidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCapacidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCapacidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 277, -1));

        lblCodigoCpu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCodigoCpu.setText("Codigo CPU:");
        getContentPane().add(lblCodigoCpu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 150, -1));

        txtCodigoCPU.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCodigoCPU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoCPUKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigoCPU, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 80, -1));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar11ActionPerformed
        this.lblIngresar.setVisible(false);
        this.lblModificar.setVisible(true);
        this.lblCodigo.setVisible(true);
        this.lblCodigoMarca.setVisible(true);
        this.lblCapacidad.setVisible(true);
        this.lblCodigoCpu.setVisible(true);
        this.btnActualizar.setVisible(true);
        this.btnIngresar.setVisible(false);
        this.txtCodigoM.setVisible(true);
        this.btnBuscar.setVisible(true);
        this.txtCapacidad.setVisible(true);
         this.txtCodigoM.setVisible(true);
        this.txtCodigoCPU.setVisible(true);
        this.txtCodigo.setVisible(true);
    }//GEN-LAST:event_btnIngresar11ActionPerformed

    private void btnActualizar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar11ActionPerformed

        this.lblIngresar.setVisible(true);
        this.lblModificar.setVisible(false);
        this.lblCodigo.setVisible(false);
        this.lblCapacidad.setVisible(true);
        this.lblCodigoMarca.setVisible(true);
        this.lblCodigoCpu.setVisible(true);
        this.btnActualizar.setVisible(false);
        this.btnIngresar.setVisible(true);
        this.txtCodigoM.setVisible(true);
        this.btnBuscar.setVisible(false);
          this.txtCapacidad.setVisible(true);
         this.txtCodigoM.setVisible(true);
        this.txtCodigoCPU.setVisible(true);
        this.txtCodigo.setVisible(false);
    }//GEN-LAST:event_btnActualizar11ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();

        if((c < '0' || c > '9')) evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ResultSet rx = Conectar.getTabla("select * from memoriaram where codigoRam='"+this.txtCodigo.getText()+"'");
        try {
            if(rx.next())
            {
                this.txtCapacidad.setText(rx.getString("capacidadRam"));
                this.txtCodigoM.setText(rx.getString("codigoMarca"));
                this.txtCodigoCPU.setText(rx.getString("codigoCpu"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(memoriaRam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtCodigoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoMKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoMKeyTyped

    private void txtCapacidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCapacidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCapacidadKeyTyped

    private void txtCodigoCPUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoCPUKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoCPUKeyTyped

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        if(txtCapacidad.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Llene el campo capacidad");
            return;
        }
        
         if(this.txtCodigoM.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Llene el campo Codigo Marca");
            return;
        }
         
          if(this.txtCodigoCPU.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Llene el campo CodigoCPU");
            return;
        }

        Conectar con=new Conectar();
        Connection reg=con.getConnection();

        try
        {
            
                PreparedStatement obj=reg.prepareStatement("INSERT INTO memoriaram(capacidadRam, codigoMarca, codigoCpu) values(?,?,?)");
                obj.setString(1,this.txtCapacidad.getText().toUpperCase());
                obj.setString(2,this.txtCodigoM.getText().toUpperCase());
                obj.setString(3,this.txtCodigoCPU.getText().toUpperCase());
                obj.executeUpdate();
                JOptionPane.showMessageDialog(null, "Guardado con exito");

                this.txtCapacidad.setText("");
                this.txtCodigoM.setText("");
                this.txtCodigoCPU.setText("");
            

        }
        catch(SQLException ex)
        {
            Logger.getLogger(memoriaRam.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        Conectar con=new Conectar();
        Connection reg=con.getConnection();
        try
        {
            PreparedStatement obj=reg.prepareStatement("UPDATE memoriaram SET capacidadRam='"+this.txtCapacidad.getText().toUpperCase()+"',codigoMarca='"+this.txtCodigoM.getText().toUpperCase()+"',codigoCpu='"+this.txtCodigoCPU.getText().toUpperCase()+ "'WHERE codigoRam='"+this.txtCodigo.getText()+"'");
            obj.executeUpdate();
            JOptionPane.showMessageDialog(null, "Guardado con exito");
        }
        catch(SQLException ex)
        {
            Logger.getLogger(memoriaRam.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(memoriaRam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(memoriaRam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(memoriaRam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(memoriaRam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new memoriaRam().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar11;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar11;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoCpu;
    private javax.swing.JLabel lblCodigoMarca;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCodigoCPU;
    private javax.swing.JTextField txtCodigoM;
    // End of variables declaration//GEN-END:variables
}
