/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luisa
 */
public class Prestamo extends javax.swing.JFrame {

    /**
     * Creates new form Prestamo
     */
    int HoraI, HoraF;
    String FechaI="", FechaF="";
    public Prestamo() {
        initComponents();
        mostrar();
        String sql = "";
        
        try
        {                 
        Conectar con=new Conectar();
        Connection reg=con.getConnection();
        sql = "select count(*) as Count from laboratorio";
        Statement st = reg.createStatement();
        ResultSet rs = st.executeQuery(sql);
        int rows=0;
        while(rs.next())
             {
                 rows = Integer.parseInt(rs.getString("Count"));
             }
        DefaultTableModel modelo  = new DefaultTableModel(); 
            System.out.println(rows);
        for (int i=0; i<=rows;i++)
        {
        sql = "select nombreLaboratorio from laboratorio where codigoLaboratorio ='"+i+"'";
        st = reg.createStatement();
        rs = st.executeQuery(sql);
        
        while(rs.next())
             {
                 
                 modelo.addColumn(rs.getString("nombreLaboratorio"));
                 System.out.println(rs.getString("nombreLaboratorio"));   
             }
        dataPrestamos.setModel(modelo);
        }
        }
            catch (SQLException ex) {
            Logger.getLogger(empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        dataLab = new javax.swing.JTable();
        txtLabNombre = new javax.swing.JTextField();
        labelrol = new javax.swing.JLabel();
        cmbHoraFinal = new javax.swing.JComboBox<>();
        labelrol1 = new javax.swing.JLabel();
        labelrol2 = new javax.swing.JLabel();
        cmbHoraInicial = new javax.swing.JComboBox<>();
        labelrol3 = new javax.swing.JLabel();
        labelrol4 = new javax.swing.JLabel();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        fechaInicial = new com.toedter.calendar.JDateChooser();
        labelrol5 = new javax.swing.JLabel();
        chkJueves = new javax.swing.JCheckBox();
        chkLunes = new javax.swing.JCheckBox();
        chkMiercoles = new javax.swing.JCheckBox();
        chkMartes = new javax.swing.JCheckBox();
        chkViernes = new javax.swing.JCheckBox();
        chkSab = new javax.swing.JCheckBox();
        chkDomingo = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        dataPrestamos = new javax.swing.JTable();
        btnIngresar = new javax.swing.JButton();
        fechaBusqueda = new com.toedter.calendar.JDateChooser();
        btnIngresar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dataLab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dataLab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataLabMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(dataLab);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 270, 80));

        txtLabNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtLabNombre.setEnabled(false);
        jPanel2.add(txtLabNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 140, 30));

        labelrol.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelrol.setText("Fecha Inicial:");
        jPanel2.add(labelrol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        cmbHoraFinal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", " ", " " }));
        jPanel2.add(cmbHoraFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 90, -1));

        labelrol1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelrol1.setText("Laboratorio:");
        jPanel2.add(labelrol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        labelrol2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelrol2.setText("Días:");
        jPanel2.add(labelrol2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        cmbHoraInicial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00 AM", "7:00 AM", "8:00 AM", "9:00 AM", "10:00 AM", "11:00 AM", "12:00 PM", "1:00 PM", "2:00 PM", "3:00 PM", "4:00 PM", "5:00 PM", "6:00 PM", "7:00 PM", "8:00 PM", " " }));
        jPanel2.add(cmbHoraInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 90, -1));

        labelrol3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelrol3.setText("Hora Inicial:");
        jPanel2.add(labelrol3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        labelrol4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelrol4.setText("Hora Final:");
        jPanel2.add(labelrol4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));

        fechaFinal.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(fechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        fechaInicial.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(fechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        labelrol5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        labelrol5.setText("Fecha Final:");
        jPanel2.add(labelrol5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        chkJueves.setText("Jueves");
        jPanel2.add(chkJueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        chkLunes.setText("Lunes");
        jPanel2.add(chkLunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        chkMiercoles.setText("Miercoles");
        chkMiercoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMiercolesActionPerformed(evt);
            }
        });
        jPanel2.add(chkMiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, -1, -1));

        chkMartes.setText("Martes");
        chkMartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMartesActionPerformed(evt);
            }
        });
        jPanel2.add(chkMartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        chkViernes.setText("Viernes");
        chkViernes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkViernesActionPerformed(evt);
            }
        });
        jPanel2.add(chkViernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        chkSab.setText("Sabado");
        jPanel2.add(chkSab, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        chkDomingo.setText("Domingo");
        jPanel2.add(chkDomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, -1));

        dataPrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        dataPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataPrestamosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(dataPrestamos);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 550, 310));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIngresar.setText("Reservar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        fechaBusqueda.setDateFormatString("yyyy-MM-dd");
        jPanel2.add(fechaBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, -1, -1));

        btnIngresar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIngresar1.setText("Hoy");
        btnIngresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnIngresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 57, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataLabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataLabMouseClicked
        int fila=this.dataLab.getSelectedRow();
        if(fila>=0)
        {
            this.txtLabNombre.setText(this.dataLab.getValueAt(fila, 0).toString());
        }

    }//GEN-LAST:event_dataLabMouseClicked

    private void chkMartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMartesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMartesActionPerformed

    private void chkMiercolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMiercolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMiercolesActionPerformed

    private void chkViernesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkViernesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkViernesActionPerformed

    private void dataPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataPrestamosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_dataPrestamosMouseClicked
    int x;
    private int Hora(String Hora)
    {
        if(Hora.equals("6:00 AM"))
        x=600;
        if(Hora.equals("7:00 AM"))
        x=700;
        if(Hora.equals("8:00 AM"))
        x=800;
        if(Hora.equals("9:00 AM"))
        x=900;
        if(Hora.equals("10:00 AM"))
        x=1000;
        if(Hora.equals("11:00 AM"))
        x=1100;
        if(Hora.equals("12:00 PM"))
        x=1200;
        if(Hora.equals("1:00 PM"))
        x=1300;
        if(Hora.equals("2:00 PM"))
        x=1400;
        if(Hora.equals("3:00 PM"))
        x=1500;
        if(Hora.equals("4:00 PM"))
        x=1600;
        if(Hora.equals("5:00 PM"))
        x=1700;
        if(Hora.equals("6:00 PM"))
        x=1800;
        if(Hora.equals("7:00 PM"))
        x=1900;
        if(Hora.equals("8:00 PM"))
        x=2000; 
        return x;
    }
            
    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
      
       HoraI=Hora(this.cmbHoraInicial.getSelectedItem().toString());
       HoraF=Hora(this.cmbHoraFinal.getSelectedItem().toString());
       FechaI=this.fechaInicial.get.toString();
        
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnIngresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar1ActionPerformed
        
    }//GEN-LAST:event_btnIngresar1ActionPerformed
     private void mostrar()
    {
        DefaultTableModel modelo2 = new DefaultTableModel();
        ResultSet rx = Conectar.getTabla("select * from laboratorio");
        modelo2.setColumnIdentifiers(new Object[]{"Nombre Lab","Capacidad Lab"});
        try
        {
            while(rx.next()){
                modelo2.addRow(new Object[]{rx.getString("nombreLaboratorio"), rx.getString("capacidadLaboratorio")});
                
            }
            this.dataLab.setModel(modelo2);
        }
        catch(Exception e){
            System.out.println(e);
        }
    }
     private void listar()
     {

     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar1;
    private javax.swing.JCheckBox chkDomingo;
    private javax.swing.JCheckBox chkJueves;
    private javax.swing.JCheckBox chkLunes;
    private javax.swing.JCheckBox chkMartes;
    private javax.swing.JCheckBox chkMiercoles;
    private javax.swing.JCheckBox chkSab;
    private javax.swing.JCheckBox chkViernes;
    private javax.swing.JComboBox<String> cmbHoraFinal;
    private javax.swing.JComboBox<String> cmbHoraInicial;
    private javax.swing.JTable dataLab;
    private javax.swing.JTable dataPrestamos;
    private com.toedter.calendar.JDateChooser fechaBusqueda;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicial;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelrol;
    private javax.swing.JLabel labelrol1;
    private javax.swing.JLabel labelrol2;
    private javax.swing.JLabel labelrol3;
    private javax.swing.JLabel labelrol4;
    private javax.swing.JLabel labelrol5;
    private javax.swing.JTextField txtLabNombre;
    // End of variables declaration//GEN-END:variables
}
