/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauricio
 */
public class tipoPeriferico extends javax.swing.JFrame {

    /**
     * Creates new form memoriaRam
     */
    public tipoPeriferico() {
        initComponents();
        
         this.lblIngresar.setVisible(false);
        this.lblModificar.setVisible(false);
        this.lblCodigo.setVisible(false);
        this.lblCapacidad.setVisible(false);
        this.btnActualizar.setVisible(false);
        this.btnIngresar.setVisible(false);
        this.txtNombre.setVisible(false);
        this.btnBuscar.setVisible(false);
        this.txtCodigo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIngresar = new javax.swing.JLabel();
        lblModificar = new javax.swing.JLabel();
        btnIngresar11 = new javax.swing.JButton();
        btnActualizar11 = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblCapacidad = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIngresar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblIngresar.setText("Registrar tipo de Periférico");
        getContentPane().add(lblIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        lblModificar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblModificar.setText("Modificar tipo de Periférico");
        getContentPane().add(lblModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, -1, -1));

        btnIngresar11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIngresar11.setText("Modificar");
        btnIngresar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresar11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        btnActualizar11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnActualizar11.setText("Registrar");
        btnActualizar11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCodigo.setText("Codigo Periferico:");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 110, -1));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 110, -1));

        lblCapacidad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCapacidad.setText("Nombre Periferico:");
        getContentPane().add(lblCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 200, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 277, -1));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 470, -1, -1));

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 470, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresar11ActionPerformed
        this.lblIngresar.setVisible(false);
        this.lblModificar.setVisible(true);
        this.lblCodigo.setVisible(true);
        this.lblCapacidad.setVisible(true);
        this.btnActualizar.setVisible(true);
        this.btnIngresar.setVisible(false);
        this.btnBuscar.setVisible(true);
        this.txtNombre.setVisible(true);
        this.txtCodigo.setVisible(true);
    }//GEN-LAST:event_btnIngresar11ActionPerformed

    private void btnActualizar11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar11ActionPerformed

        this.lblIngresar.setVisible(true);
        this.lblModificar.setVisible(false);
        this.lblCodigo.setVisible(false);
        this.lblCapacidad.setVisible(true);
        this.btnActualizar.setVisible(false);
        this.btnIngresar.setVisible(true);
        this.btnBuscar.setVisible(false);
          this.txtNombre.setVisible(true);
        this.txtCodigo.setVisible(false);
    }//GEN-LAST:event_btnActualizar11ActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        char c = evt.getKeyChar();

        if((c < '0' || c > '9')) evt.consume();
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        ResultSet rx = Conectar.getTabla("select * from tipoPeriferico where codigoTipoPeriferico='"+this.txtCodigo.getText()+"'");
        try {
            if(rx.next())
            {
                this.txtNombre.setText(rx.getString("nombrePeriferico"));
            }

        } catch (SQLException ex) {
            Logger.getLogger(tipoPeriferico.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed

        if(txtNombre.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Llene el campo nombre");
            return;
        }
        
        Conectar con=new Conectar();
        Connection reg=con.getConnection();

        try
        {
            
                PreparedStatement obj=reg.prepareStatement("INSERT INTO tipoPeriferico(nombrePeriferico) values(?)");
                obj.setString(1,this.txtNombre.getText().toUpperCase());
                obj.executeUpdate();
                JOptionPane.showMessageDialog(null, "Guardado con exito");
                this.txtNombre.setText("");
            

        }
        catch(SQLException ex)
        {
            Logger.getLogger(tipoPeriferico.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

        Conectar con=new Conectar();
        Connection reg=con.getConnection();
        try
        {
            PreparedStatement obj=reg.prepareStatement("UPDATE tipoPeriferico SET nombrePeriferico='"+this.txtNombre.getText().toUpperCase()+ "'WHERE codigoTipoPeriferico='"+this.txtCodigo.getText()+"'");
            obj.executeUpdate();
            JOptionPane.showMessageDialog(null, "Guardado con exito");
        }
        catch(SQLException ex)
        {
            Logger.getLogger(tipoPeriferico.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tipoPeriferico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tipoPeriferico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tipoPeriferico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tipoPeriferico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tipoPeriferico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar11;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnIngresar11;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblModificar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
